# Generated by Django 2.1.7 on 2019-04-16 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20190414_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='FYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
        migrations.CreateModel(
            name='GWL_inputs',
            fields=[
                ('state', models.CharField(choices=[['RJ', 'RJ']], default='State', max_length=9)),
                ('district', models.CharField(choices=[['Ajmer', 'Ajmer']], default='District', max_length=9)),
                ('block', models.CharField(choices=[['Masuda', 'Masuda'], ['Peesangan', 'Peesangan'], ['Arain', 'Arain'], ['Srinagar', 'Srinagar'], ['Jawaja', 'Jawaja'], ['Bhinay', 'Bhinay'], ['Kekri', 'Kekri'], ['Kishangarh', 'Kishangarh']], default='Block_Name', max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[['---', '---']], default='---', max_length=15)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.GWL_inputs')),
            ],
        ),
    ]
